test:stable:
    image: rust:latest
    before_script:
        - rustc --version && cargo --version
        - rustup component add rustfmt
        - rustup component add clippy
    script:
        - cargo check
        - cargo fmt -- --check
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo test
